/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PolicyRouteImport } from './routes/policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as BoekenRouteImport } from './routes/boeken'
import { Route as BehandelingenRouteImport } from './routes/behandelingen'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyRoute = PolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const BoekenRoute = BoekenRouteImport.update({
  id: '/boeken',
  path: '/boeken',
  getParentRoute: () => rootRouteImport,
} as any)
const BehandelingenRoute = BehandelingenRouteImport.update({
  id: '/behandelingen',
  path: '/behandelingen',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/behandelingen': typeof BehandelingenRoute
  '/boeken': typeof BoekenRoute
  '/classes': typeof ClassesRoute
  '/contact': typeof ContactRoute
  '/policy': typeof PolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/behandelingen': typeof BehandelingenRoute
  '/boeken': typeof BoekenRoute
  '/classes': typeof ClassesRoute
  '/contact': typeof ContactRoute
  '/policy': typeof PolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/behandelingen': typeof BehandelingenRoute
  '/boeken': typeof BoekenRoute
  '/classes': typeof ClassesRoute
  '/contact': typeof ContactRoute
  '/policy': typeof PolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/behandelingen'
    | '/boeken'
    | '/classes'
    | '/contact'
    | '/policy'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/behandelingen'
    | '/boeken'
    | '/classes'
    | '/contact'
    | '/policy'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/behandelingen'
    | '/boeken'
    | '/classes'
    | '/contact'
    | '/policy'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BehandelingenRoute: typeof BehandelingenRoute
  BoekenRoute: typeof BoekenRoute
  ClassesRoute: typeof ClassesRoute
  ContactRoute: typeof ContactRoute
  PolicyRoute: typeof PolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy': {
      id: '/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof PolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boeken': {
      id: '/boeken'
      path: '/boeken'
      fullPath: '/boeken'
      preLoaderRoute: typeof BoekenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/behandelingen': {
      id: '/behandelingen'
      path: '/behandelingen'
      fullPath: '/behandelingen'
      preLoaderRoute: typeof BehandelingenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BehandelingenRoute: BehandelingenRoute,
  BoekenRoute: BoekenRoute,
  ClassesRoute: ClassesRoute,
  ContactRoute: ContactRoute,
  PolicyRoute: PolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
